# These are the locations of your .spec files (descendants are searched too)
roots = ["ReplicatedStorage/TS/my-tests"]

[extraOptions]
# Optionally, an extraOptions table can be passed to TestBootstrap